name: Latest book list from a goodreads
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:

  update-readme-with-goodreads-books-reading:
    name: Update this repo's README with books I'm currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          comment_tag_name: "<-- READING_LIST -->"
          goodreads_user_id: "18545177"
          shelf: "currently-reading"
  
  update-readme-with-goodreads-books-read:
    name: Update this repo's README with books I read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          comment_tag_name: "<-- READ_LIST -->"
          goodreads_user_id: "18545177"
          shelf: "currently-reading"
